### ISSUE TITLE
task: Convert Integration tests

### ISSUE THREAD

**Issue by dgarros** [opsmill/infrahub-sdk-python#187]
### Component

Python SDK

### Task Description

Since the migration to its own repo, the integration have been disabled because they were relying on Infrahub internal code.
Since #183, there is a new way to write integration tests leveraging `infrahub-testcontainers`

We need to convert or cleanup all tests under `tests/integration` to work with the new format. 

- [ ] [test_node.py](https://github.com/opsmill/infrahub-sdk-python/blob/develop/tests/integration/test_node.py)
- [ ] [test_object_store.py](https://github.com/opsmill/infrahub-sdk-python/blob/develop/tests/integration/test_object_store.py)
- [ ] [test_schema.py](https://github.com/opsmill/infrahub-sdk-python/blob/develop/tests/integration/test_schema.py)
- [ ] [test_infrahub_client.py](https://github.com/opsmill/infrahub-sdk-python/blob/develop/tests/integration/test_infrahub_client.py)
- [ ] [test_infrahub_client_sync.py](https://github.com/opsmill/infrahub-sdk-python/blob/develop/tests/integration/test_infrahub_client_sync.py)
- [ ] [test_export_import.py](https://github.com/opsmill/infrahub-sdk-python/blob/develop/tests/integration/test_export_import.py) 

The first couple of tests in `test_node.py` have been converted already as an example.
